apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: prod
spec:
  provider: azure
  parameters:
    # This is for the old pod-identity, not Workload Identity
    usePodIdentity: "false"
    # This is for the node identity
    useVMManagedIdentity: "false"
    # The CLIENT ID of your User Assigned Identity from Terraform
    userAssignedIdentityID: "${azurerm_user_assigned_identity.app_identity.client_id}"
    keyvaultName: "${azurerm_key_vault.kv.name}"
    # The Tenant ID where the Key Vault is
    tenantId: "${azurerm_key_vault.kv.tenant_id}"
    objects: |
      array:
        - |
          objectName: redis-conn-string
          objectType: secret
        - |
          objectName: cosmos-conn-string
          objectType: secret