apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-service.fullname" . }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-service.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true" # trigger mutation and necessary for the pods to authenticate with Azure AD.
    spec:
      serviceAccountName: {{ include "backend-service.serviceAccountName" . }}
      # Automatically mount a ServiceAccount's API credentials, meaning the pod will run kubectl commands on the cluster which is a security risk
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext: 
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          
          # Inject Environment Variables dynamically
          env:
          - name: NODE_ENV
            value: "production"
        {{- range .Values.secretProvider.secrets }}
          - name: {{ .envKey }}
            valueFrom:
              secretKeyRef:
              # $sign ,represents absoluate path which always points to root, is used for the current context since inside the range loop, we are in a list context
                name: {{ $.Values.secretProvider.secretName }}
                key: {{ .envKey }}
        {{- end }}

          # Setup for Secrets Store CSI Driver (Volume Mounts)
          volumeMounts:
          - name: secrets-volume
            mountPath: "/mnt/secrets-store"
            readOnly: true

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          # liveness and readiness probes do not start until startup succeeds to not cause interference
          startupProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}

          readinessProbe: # know when a container is ready to start accepting traffic
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.probes.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds | default 2 }}
            failureThreshold: {{ .Values.probes.failureThreshold | default 3 }}

          livenessProbe: # indicate unrecoverable application failure, for example a deadlock.
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.probes.periodSeconds | default 10 }}
            failureThreshold: {{ .Values.probes.failureThreshold | default 3 }} # This ensures the pods is observed as a not ready for a period of time before it's hard killed

      # Setup for Secrets Store CSI Driver (Volumes)
      volumes:
        - name: secrets-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "backend-service.fullname" . }}-secrets