apiVersion: secrets-store.csi.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "backend-service.fullname" . }}-secrets
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
  # We are using workload identity to authenticate with Azure AD, so we don't need to use pod identity or VM managed identity
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    # Always quote IDs to prevent YAML parsing errors
    userAssignedIdentityID: {{ .Values.serviceAccount.clientId | quote }}
    keyvaultName: {{ .Values.secretProvider.keyvaultName | quote }}
    tenantId: {{ .Values.secretProvider.tenantID | quote }}
    objects: |
      array:
        {{- range .Values.secretProvider.secrets }}
        - |
          objectName: {{ .remoteName }}
          objectType: {{ .type | default "secret" }}
          objectAlias: {{ .remoteName }}
        {{- end }}
    
  secretObjects:
  - secretName: {{ .Values.secretProvider.secretName }}
    type: Opaque
    data:
      {{- range .Values.secretProvider.secrets }}
      - key: {{ .envKey }}
        objectName: {{ .remoteName }}
      {{- end }}